// History Repository Contract
// Feature: 003-local-storage
//
// This file defines the interface contract for the HistoryRepository.
// Implementation will be in lib/src/features/history/data/history_repository.dart

/// Transfer status enumeration.
enum TransferStatus { completed, failed, cancelled }

/// Transfer direction enumeration.
enum TransferDirection { sent, received }

/// Data transfer object for creating new history entries.
///
/// Use this when logging a completed transfer. The `id` and `timestamp`
/// will be auto-generated by the repository.
class NewTransferHistoryEntry {
  const NewTransferHistoryEntry({
    required this.transferId,
    required this.fileName,
    required this.fileCount,
    required this.totalSize,
    required this.fileType,
    required this.status,
    required this.direction,
    required this.remoteDeviceAlias,
  });

  final String transferId;
  final String fileName;
  final int fileCount;
  final int totalSize;
  final String fileType;
  final TransferStatus status;
  final TransferDirection direction;
  final String remoteDeviceAlias;
}

/// Repository for managing transfer history persistence.
///
/// Provides methods to add history entries and watch all history as a
/// live stream. History entries are ordered by timestamp (newest first).
abstract interface class IHistoryRepository {
  // ============================================================
  // Write Operations
  // ============================================================

  /// Adds a new transfer history entry.
  ///
  /// The entry will be assigned an auto-incremented `id` and the current
  /// `timestamp` automatically.
  ///
  /// Returns the generated `id` of the new entry.
  ///
  /// Example:
  /// ```dart
  /// final id = await repository.addEntry(
  ///   NewTransferHistoryEntry(
  ///     transferId: 'abc123-uuid',
  ///     fileName: 'photo.jpg',
  ///     fileCount: 1,
  ///     totalSize: 1024000,
  ///     fileType: 'image',
  ///     status: TransferStatus.completed,
  ///     direction: TransferDirection.sent,
  ///     remoteDeviceAlias: 'iPhone',
  ///   ),
  /// );
  /// ```
  Future<int> addEntry(NewTransferHistoryEntry entry);

  // ============================================================
  // Read Operations
  // ============================================================

  /// Watches all transfer history entries as a live-updating stream.
  ///
  /// Entries are ordered by timestamp (newest first).
  /// The stream emits a new list whenever the history changes.
  ///
  /// This is the primary method for displaying history in the UI.
  ///
  /// Example:
  /// ```dart
  /// repository.watchAllEntries().listen((entries) {
  ///   print('History updated: ${entries.length} entries');
  /// });
  /// ```
  Stream<List<TransferHistoryEntry>> watchAllEntries();

  /// Gets all transfer history entries (one-time read).
  ///
  /// Entries are ordered by timestamp (newest first).
  /// Use this for export or one-time access; prefer `watchAllEntries` for UI.
  Future<List<TransferHistoryEntry>> getAllEntries();

  /// Gets a single history entry by its ID.
  ///
  /// Returns `null` if no entry exists with the given ID.
  Future<TransferHistoryEntry?> getEntryById(int id);
}

/// Represents a stored transfer history entry (read from database).
///
/// This is the full entity with all fields including auto-generated
/// `id` and `timestamp`.
class TransferHistoryEntry {
  const TransferHistoryEntry({
    required this.id,
    required this.transferId,
    required this.fileName,
    required this.fileCount,
    required this.totalSize,
    required this.fileType,
    required this.timestamp,
    required this.status,
    required this.direction,
    required this.remoteDeviceAlias,
  });

  final int id;
  final String transferId;
  final String fileName;
  final int fileCount;
  final int totalSize;
  final String fileType;
  final DateTime timestamp;
  final TransferStatus status;
  final TransferDirection direction;
  final String remoteDeviceAlias;
}
