import 'package:flux/src/features/receive/domain/session_status.dart';
import 'package:flux/src/features/receive/domain/transfer_metadata.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'transfer_session.freezed.dart';

/// An active transfer session created after successful handshake.
///
/// Sessions are created when a handshake is accepted and expire after
/// 5 minutes of inactivity.
@freezed
class TransferSession with _$TransferSession {
  /// Creates a new [TransferSession] instance.
  const factory TransferSession({
    /// Unique session ID (UUID) generated by the server.
    required String sessionId,

    /// Transfer metadata from the handshake request.
    required TransferMetadata metadata,

    /// When the session was created.
    required DateTime createdAt,

    /// Current session status.
    required SessionStatus status,

    /// Failure reason if status is [SessionStatus.failed].
    String? failureReason,
  }) = _TransferSession;

  const TransferSession._();

  /// Session timeout duration (5 minutes).
  static const timeout = Duration(minutes: 5);

  /// Whether the session has expired.
  bool get isExpired {
    return DateTime.now().difference(createdAt) > timeout;
  }

  /// Creates a new pending session from handshake metadata.
  factory TransferSession.create({
    required String sessionId,
    required TransferMetadata metadata,
  }) {
    return TransferSession(
      sessionId: sessionId,
      metadata: metadata,
      createdAt: DateTime.now(),
      status: SessionStatus.pending,
    );
  }
}
