import 'package:flux/src/features/history/domain/transfer_direction.dart';
import 'package:flux/src/features/history/domain/transfer_status.dart';

/// Data transfer object for creating new history entries.
///
/// Use this when logging a completed transfer. The `id` and `timestamp`
/// will be auto-generated by the repository.
class NewTransferHistoryEntry {
  /// Creates a [NewTransferHistoryEntry].
  const NewTransferHistoryEntry({
    required this.transferId,
    required this.fileName,
    required this.fileCount,
    required this.totalSize,
    required this.fileType,
    required this.status,
    required this.direction,
    required this.remoteDeviceAlias,
  });

  /// UUID identifying the transfer session.
  final String transferId;

  /// Name of transferred file/folder.
  final String fileName;

  /// Number of files (>1 for folders).
  final int fileCount;

  /// Total size in bytes.
  final int totalSize;

  /// File type identifier (e.g., "pdf", "image", "folder").
  final String fileType;

  /// Completion status (completed, failed, cancelled).
  final TransferStatus status;

  /// Whether sent or received.
  final TransferDirection direction;

  /// Name of the other device.
  final String remoteDeviceAlias;
}
